[package]
authors = ["semenInRussia"]
name = "org_roam_fetch"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "0.2", features = ["rt-threaded", "macros"] }
quaint = {version = "0.1.13", features = ["pooled", "sqlite"]}
dotenvy = "0.15"